function escHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function qsParam(name) {
  try {
    const url = new URL(window.location.href);
    return url.searchParams.get(name) || "";
  } catch {
    return "";
  }
}

async function loadTailoredResumeByKey(key) {
  const resp = await chrome.storage.local.get("tailoredResumes");
  const all = resp?.tailoredResumes || {};
  const entry = all[key] || null;
  return entry?.tailoredResume || null;
}

function formatContact(basics) {
  const parts = [];
  if (basics?.email) parts.push(basics.email);
  if (basics?.phone) parts.push(basics.phone);
  if (basics?.location) parts.push(basics.location);
  const links = basics?.links || {};
  const linkParts = [links.linkedin, links.github, links.portfolio, links.website].filter(Boolean);
  if (linkParts.length) parts.push(linkParts.join(" | "));
  return parts.join("\n");
}

function renderSkills(skills) {
  const categories = skills?.categories && typeof skills.categories === "object" ? skills.categories : {};
  const entries = Object.entries(categories);
  if (entries.length === 0) return "<div class=\"skillCat\">No skills provided.</div>";
  const cols = entries.slice(0, 12).map(([k, v]) => {
    const items = Array.isArray(v) ? v.slice(0, 18).join(", ") : "";
    return `<div class="skillCat"><strong>${escHtml(k)}:</strong> ${escHtml(items)}</div>`;
  }).join("");
  return `<div class="skillsGrid">${cols}</div>`;
}

function renderExperience(experience) {
  const roles = Array.isArray(experience) ? experience : [];
  if (roles.length === 0) return "<p class=\"roleMeta\">No experience entries.</p>";
  return roles.slice(0, 10).map((r) => {
    const title = r?.title || "";
    const company = r?.company || "";
    const loc = r?.location || "";
    const start = r?.startDate || "";
    const end = r?.endDate || "";
    const dates = [start, end].filter(Boolean).join(" – ");
    const meta = [company, loc].filter(Boolean).join(" • ");
    const bullets = Array.isArray(r?.bullets) ? r.bullets.slice(0, 8) : [];
    const bulletHtml = bullets.length
      ? `<ul>${bullets.map((b) => `<li>${escHtml(b)}</li>`).join("")}</ul>`
      : "";
    return `
      <div class="role">
        <div class="roleHead">
          <div>
            <p class="roleTitle">${escHtml(title)}</p>
            <div class="roleMeta">${escHtml(meta)}</div>
          </div>
          <div class="roleDates">${escHtml(dates)}</div>
        </div>
        ${bulletHtml}
      </div>
    `;
  }).join("");
}

function renderResume(resume) {
  const root = document.getElementById("root");
  if (!root) return;

  const basics = resume?.basics || {};
  const name = basics?.name || "Tailored Resume";
  const headline = resume?.headline || "";
  const summaryBullets = Array.isArray(resume?.summaryBullets) ? resume.summaryBullets.slice(0, 6) : [];

  root.innerHTML = `
    <div class="top">
      <div>
        <h1>${escHtml(name)}</h1>
        ${headline ? `<div class="headline">${escHtml(headline)}</div>` : ""}
      </div>
      <div class="contact">${escHtml(formatContact(basics))}</div>
    </div>
    <div class="rule"></div>

    ${summaryBullets.length ? `
      <div class="section">
        <div class="sectionTitle">Summary</div>
        <ul>${summaryBullets.map((b) => `<li>${escHtml(b)}</li>`).join("")}</ul>
      </div>
    ` : ""}

    <div class="section">
      <div class="sectionTitle">Skills</div>
      ${renderSkills(resume?.skills)}
    </div>

    <div class="section">
      <div class="sectionTitle">Experience</div>
      ${renderExperience(resume?.experience)}
    </div>

    <div class="smallNote">Generated by AI Job Assistant (Experimental).</div>
  `;
}

async function init() {
  const key = qsParam("k");
  if (!key) {
    document.getElementById("root").textContent = "Missing resume key.";
    return;
  }
  const resume = await loadTailoredResumeByKey(key);
  if (!resume) {
    document.getElementById("root").textContent = "Tailored resume not found in storage.";
    return;
  }
  renderResume(resume);
}

init().catch((e) => {
  const root = document.getElementById("root");
  if (root) root.textContent = e?.message || "Failed to render.";
});

